name: "Bug report (CrossWatch)"
description: "Report a problem with CrossWatch sync/scrobble/UI."
title: "[bug] <short summary>"
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Before you hit “Submit”
        Please do this first, it saves both of us time:

        1. **Simplify your setup first.**  
           Enable **only the pair that’s causing trouble** and disable/remove the rest.  

        2. Go to **Settings → Maintenance**  
           Enable **Debug** and **MOD Debug**.

        3. **Reproduce the issue again** after enabling debug.
        
        4. Collect logs from **both places**:
           - **Docker console logs**
           - **CrossWatch Sync Output**
           
        5. If the issue is “some items don’t sync”:  
           run the **Analyzer** first. It often tells you what’s missing and why.

  - type: markdown
    attributes:
      value: |
        **Please don't paste secrets** (tokens, usernames, API keys, etc.).
          If the field was filled in → replace with `<REDACTED>`

  - type: input
    id: version
    attributes:
      label: CrossWatch version
      description: From Settings → About (e.g., v0.x.y) or paste short commit SHA.
      placeholder: v0.x.y or 8-char SHA
    validations:
      required: true

  - type: checkboxes
    id: providers
    attributes:
      label: Connected providers involved
      options:
        - label: Plex
        - label: Emby
        - label: Jellyfin
        - label: MDBlist
        - label: Tautulli
        - label: AniList
        - label: Trakt
        - label: SIMKL
        - label: CrossWatch Internal Tracker (CW)

  - type: input
    id: server_version
    attributes:
      label: Media server version (if applicable)
      placeholder: "Plex 1.41.x / Jellyfin 10.9.x / Emby 4.x / Tautulli 2.x"

  - type: checkboxes
    id: areas
    attributes:
      label: Affected area(s)
      options:
        - label: Synchronization → Watchlist
        - label: Synchronization → Ratings
        - label: Synchronization → History
        - label: Scrobble/Webhook
        - label: Scrobble/Watcher
        - label: Scheduler
        - label: Web UI (modals, pairs, progress)
        - label: Metadata / IDs
        - label: Config / API

  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Clear and concise description of the problem.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Attach a file or paste an excerpt (redact tokens).
        Docker:
        `docker logs crosswatch --since=30m > crosswatch.log`
      render: bash

  - type: checkboxes
    id: tried
    attributes:
      label: Troubleshooting already tried
      description: |
        Clean Everything in Maintenance. This will reset your state etc.
      options:
        - label: Settings → Maintenance → Clean Everything
        - label: Retried on latest CrossWatch version
        - label: Re-ran the same pair one-way
        - label: Restarted container  (to rule out transient issues)
